### ISSUE TITLE
Not able to connect to backend

### ISSUE THREAD

**Issue by psschand16** [staart/ui#1349]
I am running both staart UI and API on my laptop

I am able to run them successfully, they  frontend is not connecting to the backend.
I get the following error

<img width="509" alt="image" src="https://user-images.githubusercontent.com/61744673/163725984-a3ea6855-12b7-4930-8f45-ed830336fc83.png">

<img width="469" alt="image" src="https://user-images.githubusercontent.com/61744673/163726063-c4caffba-f6ce-4687-be37-f0d9375bfaa6.png">

The api server seems to stop
<img width="500" alt="image" src="https://user-images.githubusercontent.com/61744673/163726206-80a1b29b-0816-41ab-be1d-18a7893919bc.png">

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
