### ISSUE TITLE
Demo site is slow on Chrome/Mac

### ISSUE THREAD

**Issue by blondie63** [staart/ui#736]
I've tried to create an account on your demo site https://staart-ui.o15y.now.sh/auth/register
but does'nt works..

Is this UI multi-languages ?

Regards

**Comment by AnandChowdhary** [comment]
Can you please create an account on https://staart-demo.o15y.com/? That's the new URL, but I think I haven't updated it everywhere. Where did you get the `now.sh` link from?

**Comment by AnandChowdhary** [comment]
I see it in the README of staart/api, and I've fixed it.

**Comment by blondie63** [comment]
I've found here https://github.com/staart/api under View frontend demo link
But now it's corrected..
Registration and Login are OK with Firefox, many problems with Chrome on Mac..
What about multi-languages ?

**Comment by AnandChowdhary** [comment]
Can you please tell me what problems you're facing on Chrome with Mac? I'll make sure they're fixed!

Yes, you can configure Staart UI to work with multiple languages. Currently, it uses [nuxt-i118n](https://github.com/nuxt-community/nuxt-i18n) with English as the only language in the demo, but it has the necessary systems in place to add more languages.

**Comment by blondie63** [comment]
It's very strange, login page is fast but when i try to write my account the keyboard is very slow, more then 30 seconds for each key ! But on other tabs or windows my Chrome is super fast
And also your site with Firefox is very fast..

**Comment by AnandChowdhary** [comment]
That is indeed very strange. I'll use BrowserStack and try and test the demo site on a few different browser/OS combinations.

**Comment by blondie63** [comment]
Hi, to test better i've restard my iMac and try to use your demo as only one and first app but it's very slow and Chrome consume very much CPU, look:
<img width="876" alt="o15y-UI-slow" src="https://user-images.githubusercontent.com/1261851/76836839-c40b9100-6831-11ea-9603-de7d4935e14d.png">

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
