### ISSUE TITLE
Hitting refresh in register breaks the web app

### ISSUE THREAD

**Issue by ginocbjr** [staart/ui#745]
We have a test site here https://dev.smartreportz.com If you click Get Started for free and then register, it works fine, But if we are already in https://dev.smartreportz.com/auth/register and then refresh the page the page is broken. 

We are using nginx to host the dist folder. This behaviour does not happen in your test site https://staart-demo.o15y.com/ so this might be an nginx configuration issue in our end. So do you have an idea how to fix this?

Thanks

**Comment by AnandChowdhary** [comment]
When I go to https://dev.smartreportz.com/auth/register and refresh, it works perfectly... Weird

**Comment by AnandChowdhary** [comment]
No, I see it. Let me debug.

**Comment by AnandChowdhary** [comment]
Seems like your Nuxt.js build is either incomplete or broken. This file should exists, but doesn't, which is why it goes to the webapp: https://dev.smartreportz.com/_nuxt/fd8355a7ca04dff2ffa2.js

**Comment by ginocbjr** [comment]
I tried rebuilding the app again. Looks like it fixed the issue. Weird why that file no longer exists. Thanks Anand!
