### ISSUE TITLE
how to connect custom web app to this front end templete 

### ISSUE THREAD

**Issue by harishsg99** [staart/ui#803]

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @harishsg99. Can you tell me more about your specific requirements? You can build on top of Staart UI by adding Vue components and Nuxt pages, or do you mean using a different backend rather than Staart API?

**Comment by harishsg99** [comment]
I mean using a different backend rather that Staart API

**Comment by harishsg99** [comment]
I want to convert my ml web app into SaaS App

**Comment by harishsg99** [comment]
I mean how to use this template for above use case

**Comment by deephut** [comment]
It's just a template, you have to make modifications related to whatever your use case is.
