### ISSUE TITLE
UI differences?

### ISSUE THREAD

**Issue by mario** [staart/ui#915]
Hello, first of all thank you for working on the project. I've deployed it, but the admin UI seems significantly different from the one in the README file and there seems to be a missing public page, pricing and so on. Can you please clarify what am I missing?

**Comment by deephut** [comment]
Would like to know this too.

**Comment by deephut** [comment]
@mario It seems the master branch as updated ui and readme hasn't been updated accordingly.
This tree has the "old" UI
https://github.com/staart/ui/tree/3c8e1e27fd41c7183a5da68f908a457f17ac2a19

**Comment by mario** [comment]
Figured @deephut, but not using this - I wanted to, but lack of response is very discouraging.

**Comment by AnandChowdhary** [comment]
Sorry @mario, very overwhelmed these days. We're just finishing up a brand new version of both @staart API and UI at @koj-co and it's expected to be published with comprehensive documentation within this January! 😄

**Comment by mario** [comment]
@AnandChowdhary no worries, my response wasn't meant to go against you - I fully understand how complicated it is doing work and maintaining a complex open-source product (being an open-source maintainer myself). Thank you for everything you do! :)
